#~ Lancer l'acquisifier 
LWDAQ_run_tool Acquisifier.tcl 
#~ Settings pour les BCAMsset LWDAQ_info_BCAM(daq_password) "no_password" 
set LWDAQ_info_BCAM(ambient_exposure_seconds) "0" 
set LWDAQ_info_BCAM(counter) "0" 
set LWDAQ_info_BCAM(verbose_description) "  {Spot Position X (um)}  {Spot Position Y (um) or Line Rotation Anticlockwise (mrad)}  {Number of Pixels Above Threshold in Spot}  {Peak Intensity in Spot}  {Accuracy (um)}  {Threshold (counts)}" 
set LWDAQ_info_BCAM(flash_max_tries) "30" 
set LWDAQ_info_BCAM(flash_seconds_max) "0.1" 
set LWDAQ_info_BCAM(control) "Idle" 
set LWDAQ_info_BCAM(analysis_return_intensity) "0" 
set LWDAQ_info_BCAM(daq_image_left) "20" 
set LWDAQ_info_BCAM(analysis_show_timing) "0" 
set LWDAQ_info_BCAM(daq_image_bottom) "243" 
set LWDAQ_info_BCAM(extended_parameters) "0.6 0.9 0 1" 
set LWDAQ_info_BCAM(daq_image_right) "343" 
set LWDAQ_info_BCAM(text) ".bcam.text" 
set LWDAQ_info_BCAM(daq_source_device_type) "2" 
set LWDAQ_info_BCAM(flash_seconds_step) "0.000002" 
set LWDAQ_info_BCAM(daq_image_width) "344" 
set LWDAQ_info_BCAM(state_label) ".bcam.buttons.state" 
set LWDAQ_info_BCAM(daq_source_ip_addr) "*" 
set LWDAQ_info_BCAM(analysis_pixel_size_um) "10" 
set LWDAQ_info_BCAM(daq_image_height) "244" 
set LWDAQ_info_BCAM(window) ".bcam" 
set LWDAQ_info_BCAM(analysis_show_pixels) "0" 
set LWDAQ_info_BCAM(name) "BCAM" 
set LWDAQ_info_BCAM(daq_image_top) "1" 
set LWDAQ_info_BCAM(photo) "bcam_photo" 
set LWDAQ_info_BCAM(flash_num_tries) "0" 
set LWDAQ_info_BCAM(flash_seconds_reduce) "0.1" 
set LWDAQ_info_BCAM(file_use_daq_bounds) "0" 
set LWDAQ_info_BCAM(peak_min) "100" 
set LWDAQ_info_BCAM(zoom) "1" 
set LWDAQ_info_BCAM(analysis_return_bounds) "0" 
set LWDAQ_info_BCAM(delete_old_images) "1" 
set LWDAQ_info_BCAM(daq_device_type) "2" 
set LWDAQ_info_BCAM(file_try_header) "1" 
set LWDAQ_info_BCAM(peak_max) "180" 
set LWDAQ_info_BCAM(flash_seconds_transition) "0.000030" 
set LWDAQ_info_BCAM(daq_extended) "0" 
set LWDAQ_config_BCAM(analysis_threshold) "10 #" 
set LWDAQ_config_BCAM(daq_ip_addr) " 10.144.33.26 " 
set LWDAQ_config_BCAM(daq_flash_seconds) "0.000010" 
set LWDAQ_config_BCAM(daq_driver_socket) "5" 
set LWDAQ_config_BCAM(analysis_num_spots) "2" 
set LWDAQ_config_BCAM(image_source) "daq" 
set LWDAQ_config_BCAM(daq_subtract_background) "0" 
set LWDAQ_config_BCAM(daq_adjust_flash) "0" 
set LWDAQ_config_BCAM(daq_source_device_element) "3 4" 
set LWDAQ_config_BCAM(daq_source_mux_socket) "1" 
set LWDAQ_config_BCAM(file_name) "./images/BCAM*" 
set LWDAQ_config_BCAM(intensify) "exact" 
set LWDAQ_config_BCAM(memory_name) "BCAM_0" 
set LWDAQ_config_BCAM(daq_source_driver_socket) "8" 
set LWDAQ_config_BCAM(analysis_enable) "1" 
set LWDAQ_config_BCAM(verbose_result) "0" 
set LWDAQ_config_BCAM(daq_device_element) "2" 
set LWDAQ_config_BCAM(daq_mux_socket) "1" 
